language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base
  - source /opt/qt*/bin/qt*-env.sh
  - sudo apt-get -y install libzip-dev liblzma-dev libarchive-dev libarchive

script:
  - cd tests
  - qmake .
  - make -j$(nproc)
  - ./tests # Run Tests
