language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base
  - source /opt/qt*/bin/qt*-env.sh
  - sudo apt-get -y install libzip-dev liblzma-dev

script:
  - git clone https://github.com/libarchive/libarchive
  - cd libarchive
  - cmake .
  - make -j$(nproc)
  - sudo make install
  - sudo cp -fp /usr/local/lib/pkgconfig/libarchive.pc /usr/lib/pkgconfig/libarchive.pc
  - sudo cp -fp /usr/local/lib/libarchive.* /usr/lib/
  - cd ../tests
  - qmake .
  - make -j$(nproc)
  - ./tests # Run Tests
