language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base
  - source /opt/qt*/bin/qt*-env.sh
  - sudo apt-get -y install libzip-dev liblzma-dev 
  - wget -O libarchive.tar.gz https://libarchive.org/downloads/libarchive-3.3.2.tar.gz 
  - tar -xvf libarchive.tar.gz
  - cd libarchive-3.3.2 
  - cmake .
  - make -j$(nproc)
  - sudo make install
  - sudo cp libarchive/libarchive.so.* /usr/lib/
  - cd .. # return to the root dir.

script:
  - mkdir build ; cd build # Check if it builds as a library.
  - qmake .. 
  - make -j$(nproc)
  - cd ..
  - cd tests/
  - qmake .
  - make -j$(nproc)
  - ./tests # Run Tests
