install:
 - set QTDIR=C:\Qt\5.10.1\mingw53_32
 - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - git clone --recursive https://github.com/libarchive/libarchive
  - cd libarchive
  - cmake . -G %makefiles%
  - mingw32-make 
  - mingw32-make install
  - cd ..
  - cd tests
  - qmake
  - mingw32-make
